# Elasticsearch %%ELASTICSEARCH_VERSION%%

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM %%UPSTREAM_IMAGE_DIGEST%%

# The upstream image was built by:
#   https://github.com/elastic/elasticsearch-docker/tree/%%ELASTICSEARCH_VERSION%%

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Elasticsearch documentation visit https://www.elastic.co/guide/en/elasticsearch/reference/%%ELASTICSEARCH_VERSION%%/docker.html
