# Elasticsearch 7.0.0

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM docker.elastic.co/elasticsearch/elasticsearch:7.0.0@sha256:3ecdbe97335a39d71da60e0b935b589c43e4aefca7776ce8877e4d9f915e66ba

# The upstream image was built by:
#   https://github.com/elastic/dockerfiles/tree/v7.0.0/elasticsearch

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Elasticsearch documentation visit https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

# See https://github.com/docker-library/official-images/pull/4916 for more details.
