# Elasticsearch 6.5.1

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM docker.elastic.co/elasticsearch/elasticsearch:6.5.1@sha256:c598e8343af6a2734ae768b4d25f976c1de6c45d8d9f8dfa8a3c3448e5a85e86

# The upstream image was built by:
#   https://github.com/elastic/elasticsearch-docker/tree/6.5.1

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Elasticsearch documentation visit https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

# See https://github.com/docker-library/official-images/pull/4916 for more details.
