# Elasticsearch 6.4.0

# This image re-bundles the Docker image from the upstream provider, Elastic. 
FROM docker.elastic.co/elasticsearch/elasticsearch@sha256:2244676001fa9b12012ec1f7a51526a8d7384fcb02674e5ae29b6e637e363908

# The upstream image was built by:
#   https://github.com/elastic/elasticsearch-docker/tree/6.4.0
